language: java

jdk: openjdk8

script:
  - echo "Hola travis"
  - mvn package
  - ssh-keyscan -H ubuntu@ec2-3-20-252-36.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
  - ssh-keyscan -H 3.20.252.36 >> ~/.ssh/known_hosts
  - scp -i acceso_instancia.pem target/*.war ubuntu@ec2-3-20-252-36.us-east-2.compute.amazonaws.com:/tmp
